name: Platform Tests
on: [push, pull_request]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.12.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.5.0
      id: setup-go-faster
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libopenal-dev
      if: ${{ runner.os == 'Linux' }}

    #- name: Verify go modules
    #  run: |
    #    if [ "$GO111MODULE" == "on" ]
    #    then
    #        # For some reason `git diff-index HEAD` does not work properly if the following line is missing.
    #        git diff
    #        # check that go mod tidy does not change go.mod/go.sum
    #        go mod tidy && git diff-index --quiet HEAD -- || ( echo "go.mod/go.sum not up-to-date"; git diff-index HEAD --; false )
    #    fi

    - name: Tests
      run: go test -tags ci ./...

